import pre1 from "../assets/pre1.jpg";
import pre2 from "../assets/pre2.jpg";
import pre3 from "../assets/pre3.jpg";
import pre4 from "../assets/pre4.jpg";
import pre7 from "../assets/pre7.jpg";



const products = [
  {
    id: "1",
    image: pre7,
    title: "Title 1",
    catégorie: "Aménagements extérieurs",
    sousCatégorie: "Equipement",
    prix: "6 995",
    prixAvant: "9 440 DH",
    length: "120cm",
    width: "50cm",
    thickness: "-",
    height: "10cm",
    Weight: "100kg",
    volume: "30cm²",
    material: "bois de l'épicéa ou sapin",
  },
  {
    id: "2",
    image: pre1,
    title: "Title 2",
    catégorie: "meubles corporels",
    sousCatégorie: "Equipement",
    prix: "6 000",
    prixAvant: "8 440 DH",

    length: "170cm",
    width: "90cm",
    thickness: "-",
    height: "20cm",
    Weight: "70kg",
    volume: "50cm²",
    material: "Noyer",
  },
  {
    id: "3",
    image: pre2,
    title: "Title 3",
    catégorie: "meubles corporels",
    sousCatégorie: "Equipement",
    prix: "9 160",
    prixAvant: "11 440 DH",
    length: "750cm",
    width: "90cm",
    thickness: "-",
    height: "50cm",
    Weight: "170kg",
    volume: "900cm²",
    material: "bois de Cerisier",
  },
  {
    id: "4",
    image: pre3,
    title: "Title 4",
    catégorie: "meubles incorporels",
    sousCatégorie: "Equipement",
    prix: "6 235",
    prixAvant: "10 440 DH",

    length: "120cm",
    width: "100cm",
    thickness: "-",
    height: "100cm",
    Weight: "60kg",
    volume: "30cm²",
    material: "bois deEucalyptus ",
  },
  {
    id: "5",
    image: pre4,
    title: "Title 5",
    catégorie: "Aménagements extérieurs",
    sousCatégorie: "Equipement",
    prix: "4 875",
    length: "800cm",
    width: "60cm",
    thickness: "-",
    height: "90cm",
    Weight: "97kg",
    volume: "36cm²",
    material: "bois de l'épicéa ou sapin",
  },
  {
    id: "6",
    image: pre3,
    title: "Title 6",
    catégorie: "meubles incorporels.",
    sousCatégorie: "Equipement",
    prix: "3 465",
    prixAvant: "6 440",
    length: "120cm",
    width: "110cm",
    thickness: "-",
    height: "59cm",
    Weight: "36kg",
    volume: "40cm²",
    material: "bois de l'épicéa ou sapin",
  },
  {
    id: "7",
    image: pre7,
    title: "Title 7",
    catégorie: "Aménagements extérieurs",
    sousCatégorie: "Equipement",
    prix: "5 874",
    prixAvant: "7 963 DH",
    length: "360cm",
    width: "50cm",
    thickness: "-",
    height: "10cm",
    Weight: "10kg",
    volume: "79cm²",
    material: "bois de l'épicéa ou sapin",
  },
  {
    id: "8",
    image: pre1,
    title: "Title 8",
    catégorie: "Aménagements extérieurs",
    sousCatégorie: "Equipement",
    prix: "4 230",
    length: "122cm",
    width: "60cm",
    thickness: "-",
    height: "90cm",
    Weight: "97kg",
    volume: "75cm²",
    material: "bois de l'épicéa ou sapin",
  },
  {
    id: "9",
    image: pre2,
    title: "Title 9",
    catégorie: "meubles incorporels.",
    sousCatégorie: "Equipement",
    prix: "8 113",
    length: "220cm",
    width: "660cm",
    thickness: "-",
    height: "90cm",
    Weight: "95kg",
    volume: "120cm²",
    material: "bois de l'épicéa ou sapin",
  },
];
export default products;
